
'use server';
/**
 * @fileOverview AI flows for the Questions Creator feature.
 *
 * - generateQuestions - Generates questions based on document content.
 * - convertQuestionsToJson - Converts text-based questions to a structured JSON format.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Schema for generating questions
const GenerateQuestionsInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for generating questions.'),
  documentContent: z.string().describe('The text content extracted from the uploaded document.'),
  images: z.array(z.string()).describe("A list of images from the document, as data URIs. Expected format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type GenerateQuestionsInput = z.infer<typeof GenerateQuestionsInputSchema>;

// Schema for converting questions to JSON
const ConvertToJsonInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for JSON conversion.'),
  questionsText: z.string().describe('The text of the questions generated by the first model.'),
});
export type ConvertToJsonInput = z.infer<typeof ConvertToJsonInputSchema>;


const generateQuestionsPrompt = ai.definePrompt({
    name: 'generateQuestionsPrompt',
    input: { schema: GenerateQuestionsInputSchema },
    prompt: `
        You are an expert at creating educational material from documents.
        Follow the user's instructions precisely to generate questions from the provided document content, which includes text and images.
        Base your questions on both the text and the visual information in the images.

        USER'S PROMPT:
        {{{prompt}}}

        DOCUMENT CONTENT (TEXT):
        {{{documentContent}}}

        DOCUMENT CONTENT (IMAGES):
        {{#each images}}
        {{media url=this}}
        {{/each}}
    `,
});

export async function generateQuestions(input: GenerateQuestionsInput): Promise<string> {
    const { text } = await generateQuestionsPrompt(input);
    return text;
}


const convertToJsonPrompt = ai.definePrompt({
    name: 'convertToJsonPrompt',
    input: { schema: ConvertToJsonInputSchema },
    output: { format: 'json' },
    prompt: `
        You are a text-to-JSON conversion specialist.
        Follow the user's prompt to convert the given text into a structured JSON format.

        USER'S PROMPT:
        {{{prompt}}}

        TEXT TO CONVERT:
        {{{questionsText}}}
    `,
});

export async function convertQuestionsToJson(input: ConvertToJsonInput): Promise<string> {
    try {
        const { output } = await convertToJsonPrompt(input);

        // Case 1: The output is a structured JSON object (most common).
        if (typeof output === 'object' && output !== null) {
            return JSON.stringify(output, null, 2);
        }

        // Case 2: The output is a string that is *already* valid JSON.
        if (typeof output === 'string') {
            try {
                // Validate and re-stringify to ensure it's well-formatted.
                const parsed = JSON.parse(output);
                return JSON.stringify(parsed, null, 2);
            } catch (e) {
                // If parsing fails, it's not a valid JSON string.
                // It might be an error message or just plain text from the model.
                // In this scenario, returning it as-is can be helpful for debugging.
                console.warn("Model output was a string but not valid JSON:", output);
                throw new Error("The AI returned a response that could not be converted to JSON. Please check the generated text and try again.");
            }
        }

        // Fallback for any other unexpected type (e.g., number, boolean).
        // This provides a clear error message instead of causing a server crash.
        const errorMsg = `Could not convert to JSON. Received an unexpected type: ${typeof output}`;
        console.error(errorMsg);
        throw new Error(errorMsg);

    } catch (err) {
        console.error("Error in convertQuestionsToJson flow:", err);
        // Re-throw the error to be caught by the client-side, which will show the user an error.
        throw err;
    }
}
