
'use server';
/**
 * @fileOverview AI flows for the Questions Creator feature.
 *
 * - generateQuestions - Generates questions based on document content.
 * - convertQuestionsToJson - Converts text-based questions to a structured JSON format.
 * - repairJson - Attempts to repair a malformed JSON string.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Schema for generating questions
const GenerateQuestionsInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for generating questions.'),
  documentContent: z.string().describe('The text content extracted from the uploaded document.'),
  images: z.array(z.string()).describe("A list of images from the document, as data URIs. Expected format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type GenerateQuestionsInput = z.infer<typeof GenerateQuestionsInputSchema>;

// Schema for converting questions to JSON
const ConvertToJsonInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for JSON conversion.'),
  questionsText: z.string().describe('The text of the questions generated by the first model.'),
});
export type ConvertToJsonInput = z.infer<typeof ConvertToJsonInputSchema>;

// Schema for repairing JSON
const RepairJsonInputSchema = z.object({
  malformedJson: z.string().describe('The malformed JSON string that needs to be repaired.'),
  desiredSchema: z.string().describe('A description or schema of the desired JSON structure.'),
});
export type RepairJsonInput = z.infer<typeof RepairJsonInputSchema>;


const generateQuestionsPrompt = ai.definePrompt({
    name: 'generateQuestionsPrompt',
    input: { schema: GenerateQuestionsInputSchema },
    prompt: `
        You are an expert at creating educational material from documents.
        Follow the user's instructions precisely to generate questions from the provided document content, which includes text and images.
        Base your questions on both the text and the visual information in the images.

        USER'S PROMPT:
        {{{prompt}}}

        DOCUMENT CONTENT (TEXT):
        {{{documentContent}}}

        DOCUMENT CONTENT (IMAGES):
        {{#each images}}
        {{media url=this}}
        {{/each}}
    `,
});

export async function generateQuestions(input: GenerateQuestionsInput): Promise<string> {
    const { text } = await generateQuestionsPrompt(input);
    return text;
}


const convertToJsonPrompt = ai.definePrompt({
    name: 'convertToJsonPrompt',
    input: { schema: ConvertToJsonInputSchema },
    output: { format: 'json' },
    prompt: `
        You are a text-to-JSON conversion specialist.
        Follow the user's prompt to convert the given text into a structured JSON format.
        Your output MUST be only the JSON itself, without any surrounding text or markdown.

        USER'S PROMPT:
        {{{prompt}}}

        TEXT TO CONVERT:
        {{{questionsText}}}
    `,
});

export async function convertQuestionsToJson(input: ConvertToJsonInput): Promise<string> {
    try {
        const { output } = await convertToJsonPrompt(input);

        // Case 1: The output is already a structured JSON object.
        if (typeof output === 'object' && output !== null) {
            return JSON.stringify(output, null, 2);
        }

        // Case 2: The output is a string that might contain JSON.
        if (typeof output === 'string') {
            // Attempt to find and parse JSON from a markdown block.
            const jsonMatch = output.match(/```json\n([\s\S]*?)\n```/);
            if (jsonMatch && jsonMatch[1]) {
                try {
                    // It's already a string, just need to format it
                    const parsed = JSON.parse(jsonMatch[1]);
                    return JSON.stringify(parsed, null, 2); 
                } catch (e) {
                     // The extracted string is not valid JSON, fall through to throw an error
                }
            }

            // If not in a markdown block, try to parse the whole string directly.
            try {
                const parsed = JSON.parse(output);
                return JSON.stringify(parsed, null, 2);
            } catch (e) {
                // If parsing fails, it's not a valid JSON string.
                // This could be an error message or plain text from the model.
                console.warn("Model output was a string but not valid JSON:", output);
                // Throw a specific, catchable error with the malformed output
                 throw new Error(`The AI returned a response that could not be converted to a valid JSON structure. Raw output: ${output}`);
            }
        }

        // Fallback for any other unexpected type (e.g., number, boolean).
        const errorMsg = `Could not convert to JSON. The AI returned an unexpected data type: ${typeof output}`;
        console.error(errorMsg);
        throw new Error(errorMsg);

    } catch (err: any) {
        console.error("Error in convertQuestionsToJson flow:", err);
        // Re-throw the original error or a new one to be caught by the client-side caller.
        throw new Error(err.message || "An unexpected error occurred during JSON conversion.");
    }
}


const repairJsonPrompt = ai.definePrompt({
    name: 'repairJsonPrompt',
    input: { schema: RepairJsonInputSchema },
    output: { format: 'json' },
    prompt: `
        You are a JSON repair expert. The following string is a malformed JSON.
        Fix it so that it perfectly matches the desired schema.
        The desired schema is: {{{desiredSchema}}}

        Malformed JSON:
        {{{malformedJson}}}

        Your response MUST be only the corrected JSON content.
    `,
});

export async function repairJson(input: RepairJsonInput): Promise<string> {
    const { output } = await repairJsonPrompt(input);
    if (typeof output === 'object' && output !== null) {
        return JSON.stringify(output, null, 2);
    }
    // Attempt to parse if it's a string, similar to the main conversion function
    if (typeof output === 'string') {
        try {
            const parsed = JSON.parse(output);
            return JSON.stringify(parsed, null, 2);
        } catch (e) {
            throw new Error('The repair process also resulted in invalid JSON.');
        }
    }
    throw new Error('The repair process returned an unexpected data type.');
}
