
'use server';
/**
 * @fileOverview AI flows for the Questions Creator feature.
 *
 * - generateQuestions - Generates questions based on document content.
 * - convertQuestionsToJson - Converts text-based questions to a structured JSON format.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Schema for generating questions
const GenerateQuestionsInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for generating questions.'),
  documentContent: z.string().describe('The text content extracted from the uploaded document.'),
  images: z.array(z.string()).describe("A list of images from the document, as data URIs. Expected format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type GenerateQuestionsInput = z.infer<typeof GenerateQuestionsInputSchema>;

// Schema for converting questions to JSON
const ConvertToJsonInputSchema = z.object({
  prompt: z.string().describe('The user-defined prompt for JSON conversion.'),
  questionsText: z.string().describe('The text of the questions generated by the first model.'),
});
export type ConvertToJsonInput = z.infer<typeof ConvertToJsonInputSchema>;


const generateQuestionsPrompt = ai.definePrompt({
    name: 'generateQuestionsPrompt',
    input: { schema: GenerateQuestionsInputSchema },
    prompt: `
        You are an expert at creating educational material from documents.
        Follow the user's instructions precisely to generate questions from the provided document content, which includes text and images.
        Base your questions on both the text and the visual information in the images.

        USER'S PROMPT:
        {{{prompt}}}

        DOCUMENT CONTENT (TEXT):
        {{{documentContent}}}

        DOCUMENT CONTENT (IMAGES):
        {{#each images}}
        {{media url=this}}
        {{/each}}
    `,
});

export async function generateQuestions(input: GenerateQuestionsInput): Promise<string> {
    const { text } = await generateQuestionsPrompt(input);
    return text;
}


const convertToJsonPrompt = ai.definePrompt({
    name: 'convertToJsonPrompt',
    input: { schema: ConvertToJsonInputSchema },
    output: { format: 'json' },
    prompt: `
        You are a text-to-JSON conversion specialist.
        Follow the user's prompt to convert the given text into a structured JSON format.

        USER'S PROMPT:
        {{{prompt}}}

        TEXT TO CONVERT:
        {{{questionsText}}}
    `,
});

export async function convertQuestionsToJson(input: ConvertToJsonInput): Promise<string> {
    const { output } = await convertToJsonPrompt(input);

    // Genkit's `output: { format: 'json' }` can return a JSON object or a string.
    // We need to handle both cases to ensure a string is always returned.
    if (typeof output === 'object' && output !== null) {
        return JSON.stringify(output, null, 2);
    }
    
    // If the output is already a string (which can happen), return it directly.
    if (typeof output === 'string') {
        // Attempt to parse and re-stringify to ensure it's valid, pretty-printed JSON.
        // If parsing fails, it's likely just a string message, so return it as is.
        try {
            const parsed = JSON.parse(output);
            return JSON.stringify(parsed, null, 2);
        } catch (e) {
            return output; // It's not a JSON string, so return as is.
        }
    }
    
    // Fallback for unexpected types (like number, boolean, etc.)
    return `Could not convert to JSON. Received type: ${typeof output}`;
}
